kind: Secret
apiVersion: v1
metadata:
  name: repository-credential
  annotations:
    tekton.dev/git-0: 'https://gitlab.mininterior.gob.ar/'
# credenciales de user openshift en gitlab interno
data:
  password: SmJwd0hINEVueEZK
  username: b3BlbnNoaWZ0
type: kubernetes.io/basic-auth